[package]
name = "knopka"
version = "0.1.0"
edition = "2024"

[dependencies]
nechto = { path = "../nechto" }
tracing-subscriber = "0.3.19"

[build-dependencies]
nechto-build = { path = "../nechto-build" }
